version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: world-cafe-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "SO6mpssfLOrH5Nr^NuB%&SboZs"
      MYSQL_DATABASE: "world_cafe_platform"
      MYSQL_USER: "world_cafe_user"
      MYSQL_PASSWORD: "WorldCafe2024!"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
    networks:
      - world-cafe-network

  # World Café Platform Application
  app:
    image: alexdoit/world-cafe-platform:latest  # Updated to correct image
    container_name: world-cafe-app
    restart: unless-stopped
    ports:
      - "80:3000"  # Production port mapping
    environment:
      # Database Configuration
      DB_HOST: mysql
      DB_USER: "world_cafe_user"
      DB_PASSWORD: "WorldCafe2024!"
      DB_NAME: "world_cafe_platform"
      DB_PORT: "3306"
      DB_SSL: "false"
      
      # Server Configuration
      PORT: "3000"
      NODE_ENV: "production"
      
      # API Keys - REPLACE WITH YOUR ACTUAL KEYS
      DEEPGRAM_API_KEY: "${DEEPGRAM_API_KEY:-your_deepgram_key_here}"
      GROQ_API_KEY: "${GROQ_API_KEY:-your_groq_key_here}"
      
      # Admin Configuration
      ADMIN_PASSWORD: "${ADMIN_PASSWORD:-admin123}"
      
      # QR Code Configuration
      BASE_URL: "${BASE_URL:-http://localhost}"
      
      # Session Secret
      SESSION_SECRET: "${SESSION_SECRET:-production-secret-key-change-this}"
      
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - uploads_data:/app/uploads
      - qr_data:/app/public/qr-codes
    networks:
      - world-cafe-network

volumes:
  mysql_data:
    driver: local
  uploads_data:
    driver: local
  qr_data:
    driver: local

networks:
  world-cafe-network:
    driver: bridge